### ISSUE TITLE
Installer with problems

### ISSUE THREAD

**Issue by fnotti** [joomlatools/joomlatools-todo#10]
Hi and thanx in advance for your work...

I tryed to install it after Nooky Framwork but Joomla said

"Warning
JInstaller: :Install: File does not exist /home/foponlaxn/domains/foponline.org/public_html/tmp/install_5666fcc73734b/joomlatools-todo-master/administrator/components/com_todo/com_todo"

Then

"Message
Installation of the package was successful."

But then it dont work! when i click Componet/Todo

" Cannot load object from identifier: com:activities.controller.behavior.loggable"

Joomla 3.4.5

Best regards,

Francisco.-

**Comment by stevenrombauts** [comment]
Hi @fnotti! It sounds like you are trying to install the package using the installer UI in the back-end? 

We recommend to install using Composer as described in the [README](https://github.com/joomlatools/joomlatools-todo#installation) using the command line. That way we can fetch all dependencies (like the framework) in one go.

We don't support another method of installing this example component.

**Comment by fnotti** [comment]
Oh, sorry... yes! i'll try to do by Composer... Thnx a lot
